[tool.liccheck]
# Authorized and unauthorized licenses in lowercase - MIT and Apache preferred
authorized_licenses = [
        "apache",
        "apache 2.0",
        "apache software license",
        "apache software",
        "mit",
        "mit license",
]