config:
  azure:location: UKSouth
  azure:environment: public
  project-compliance:rg-useremailtag: emtech
  project-compliance:rg-purpose: Stretch Labs Exploration
  project-compliance:rg_environment: dev
  labs:platform: iot-hub
