name: "CLA Signing"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: cla-assistant/github-action@v2.1.1-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT_TOKEN }}
        with:
          path-to-signatures: "docs/version1/cla.json"
          path-to-document: "https://github.com/Avanade/emtech-stretch-labs/blob/545de9d059b391cbb2927bdb998fc67117642f4f/docs/contributor-licence-agreement.md" # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: "main"
          allowlist: dependabot-preview[bot],greenkeeper[bot],dependabot
