name: Run on Push to main
on:
  push:
    branches:
      - main
    paths:
      - "!docs/**"
      - "!nextmind-robot-telepresence/Library/PackageCache/**"
      - "!nextmind-robot-telepresence/Library/ScriptAssemblies/**"
jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Issues for Todos in Python Code
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          INCLUDE_PATTERN: "\\.(py)$"
  pylicence:
    runs-on: ubuntu-latest
    steps:
      - name: License Checker from py-liccheck
        uses: andersy005/gh-action-py-liccheck@main
        with:
          strategy-ini-file: ./pyproject.toml
          level: standard
          requirements-txt-file: ./requirements.txt
          no-deps: true
